---
title: "prophet-model"
author: "Margaret Reed"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-library}
library(tidyverse)
library(prophet)
library(readxl)
library(janitor)
library(lubridate)
library(scales)
library(MLmetrics)
library(timeDate)
```


```{r load-data}
data1 <- read_excel("online_retail_ii.xlsx", sheet = 1)
data2 <- read_excel("online_retail_ii.xlsx", sheet = 2)
```


```{r clean-data}
data <- data1 %>%
  rbind(data2) %>%
  clean_names()

data <- data %>%
  mutate(
    revenue = quantity*price,
    date = ymd(as.Date(invoice_date)),
    year = year(as.Date(date)),
    month = month(date),
    hour = hour(invoice_date)
    )
```

```{r}
daily_uk <- data %>%
  filter(country == "United Kingdom", revenue > 0) %>%
  group_by(date) %>%
  summarize(daily_revenue = sum(revenue))
```


```{r}
hourly_uk <- data %>%
  filter(country == "United Kingdom", revenue > 0) %>%
  group_by(date, hour) %>%
  summarize(hourly_revenue = sum(revenue), .groups = "drop")
```


```{r}
p_data <- daily_uk %>%
  filter(daily_revenue < 150000) %>%
  select(date, daily_revenue) %>%
  rename(ds = date, y = daily_revenue)


x <- dim(p_data)[1]
y <- round(x*0.7, 0)
z <- x - y

training <- p_data %>% slice_head(n=y)
validation <- p_data %>% anti_join(training) %>% slice_head(n=z/3)
testing <- p_data %>% anti_join(training) %>% slice_tail(n=(2*z/3))
```


```{r}
uk_holidays <- tibble(ds = holidayLONDON(year = 2009:2011) %>%
  as.Date(),
  holiday = "holiday")
```


# https://facebook.github.io/prophet/docs/quick_start.html#r-api

```{r}
forecast <- make_model("United Kingdom")
```


```{r}
pred_val <- forecast %>%
  slice_tail(n=z) %>%
  slice_head(n = z/3) %>%
  pull(yhat)
true_val <- validation %>%
  pull(y)

MAPE(pred_val, true_val)
```

```{r}
pred_test <- forecast %>%
  slice_tail(n=(2*z/3)) %>%
  pull(yhat)

true_test <- testing %>%
  pull(y)

MAPE(pred_test[1:40], true_test[1:40])
MAPE(pred_test[41:80], true_test[41:80])
MAPE(pred_test[81:120], true_test[81:120])


full_join(p_data, forecast) %>%
  ggplot() +
  geom_line(aes(x = ymd(ds), y = y), color = "black") +
  geom_line(aes(x = ymd(ds), y = yhat), color = "blue") +
  scale_y_continuous(labels = label_dollar(
    scale = .001, 
    suffix = "k",
    prefix = "£"
    )) +
  labs(
    x = "Date",
    y = "Revenue (sterling)",
    title = "Predicted vs actual revenue during last two months of data",
    subtitle = "Actual (black), predicted (blue)"
  ) +
  theme_minimal() +
  geom_line(data = training, aes(x = ymd(ds), y = y), color = "grey")
```

```{r}
p_data %>%
  ggplot(aes(x = y)) +
  geom_boxplot()
```

```{r}
data %>%
  group_by(date, country) %>%
  summarize(daily_revenue = sum(revenue), .groups = "drop") %>%
  count(country) %>%
  arrange(desc(n))
```


```{r}
mut_data <- p_data %>%
  mutate(
    days_since = interval(ymd("2009-12-01"), ymd(ds)) %/% days(1)
  )

model <- lm(y ~ days_since + days_since**2 + days_since**3 + days_since**4, data = mut_data)

summary(model)
```


```{r}
pred_test <- forecast %>%
  slice_tail(n=(2*z/3)) %>%
  pull(yhat)

true_test <- testing %>%
  pull(y)

MAPE(pred_test[1:40], true_test[1:40])
MAPE(pred_test[41:80], true_test[41:80])
MAPE(pred_test[81:120], true_test[81:120])
```


```{r}
s <- round(2*z/9, 0)
tibble(
 first = map2_dbl(pred_test[1:s], true_test[1:s], MAPE),
 second = map2_dbl(pred_test[(s+1):(2*s)], true_test[(s+1):(2*s)], MAPE),
third = map2_dbl(pred_test[(2*s+1):(3*s)], true_test[(2*s+1):(3*s)], MAPE)
) %>%
  pivot_longer(
    cols = everything(),
    names_to = "segment",
    values_to = "error"
  ) %>%
  ggplot(aes(x = error, y = segment)) +
  geom_boxplot()
```



