---
title: "sales-eda"
author: "Margaret Reed"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 data : https://archive.ics.uci.edu/ml/datasets/Online+Retail+II

```{r load-pkgs}
library(tidyverse)
library(readxl)
library(janitor)
library(lubridate)
library(scales)
library(forecast)
```

```{r load-data}
data <- read_excel("online_retail_ii.xlsx")
```

```{r clean-data}
data <- data %>%
  clean_names()
```

```{r}
data %>% 
  count(country) %>%
  arrange(desc(n))
```

```{r}
data %>%
  count(description) %>%
  arrange(desc(n))
```

```{r}
data %>%
  group_by(country) %>%
  summarize(
    total_quantity = sum(quantity),
    total_revenue = sum(quantity*price)
    ) %>%
  arrange(desc(total_revenue))
```

```{r}
data <- data %>%
  mutate(
    revenue = quantity*price,
    date = ymd(as.Date(invoice_date)),
    year = year(as.Date(date)),
    month = month(date),
    hour = hour(invoice_date)
    )
```

```{r}
data %>%
  filter(revenue > 0) %>%
  group_by(date, country) %>%
  summarize(daily_revenue = sum(revenue)) %>%
  filter(country == "United Kingdom") %>%
  ggplot(aes(x = date, y = daily_revenue)) +
  geom_point() +
  geom_smooth(se = F) +
  scale_y_continuous(labels = label_dollar(
    scale = .001, 
    suffix = "k",,
    prefix = "£"
    )) +
  labs(
    x = "Date", 
    y = "Daily revenue",
    title = "Daily revenue over time",
    subtitle = "In the United Kingdom"
  ) +
  theme_minimal()
```

```{r}
data %>%
  mutate(date = lubridate::ymd(as.Date(invoice_date)))
```

```{r}
data %>%
  filter(revenue > 0) %>%
  group_by(month, year, country) %>%
  summarize(monthly_revenue = sum(revenue)) %>%
  filter(country == "United Kingdom") %>%
  ggplot(aes(x = my(paste0(month, "-", year)), y = monthly_revenue)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = label_dollar(
    scale = .000001, 
    suffix = "M", 
    accuracy = .1,
    prefix = "£"
    )) +
  labs(
    x = "Date", 
    y = "Monthly revenue",
    title = "Monthly revenue over time",
    subtitle = "In the United Kingdom"
  ) +
  theme_minimal()
```


```{r}
data %>%
  filter(revenue > 0) %>%
  group_by(date, country) %>%
  summarize(daily_revenue = sum(revenue)) %>%
  filter(country == "United Kingdom") %>%
  ggplot(aes(x = date, y = daily_revenue)) +
  geom_line() +
  geom_smooth(se = F) +
  scale_y_continuous(labels = label_dollar(
    scale = .001, 
    suffix = "k",
    prefix = "£"
    )) +
  labs(
    x = "Date", 
    y = "Daily revenue",
    title = "Daily revenue over time",
    subtitle = "In the United Kingdom"
  ) +
  theme_minimal()
```

source: https://www.simplilearn.com/tutorials/data-science-tutorial/time-series-forecasting-in-r#:~:text=Time%20series%20forecasting%20is%20the,as%20a%20time%20series%20data.


```{r}
daily_uk <- data %>%
  filter(country == "United Kingdom", revenue > 0) %>%
  group_by(date) %>%
  summarize(daily_revenue = sum(revenue))
mymodel <- auto.arima(daily_uk %>% pull(daily_revenue))
```

```{r}
plot.ts(mymodel$residuals)
```

```{r}
mymodel %>% summary()
```


```{r}
myforecast <- forecast(mymodel, h=50)
plot(myforecast)
```

https://www.pluralsight.com/guides/time-series-forecasting-using-r

```{r}
hourly_uk <- data %>%
  filter(country == "United Kingdom", revenue > 0) %>%
  group_by(date, hour) %>%
  summarize(hourly_revenue = sum(revenue))
mymodel <- auto.arima(hourly_uk %>% pull(hourly_revenue))
```

```{r}
plot.ts(mymodel$residuals)
```

```{r}
myforecast <- forecast(mymodel, h=1000)
plot(myforecast)
```






```{r}
training <- daily_uk %>%
  slice(1:276)
testing <- daily_uk %>%
  slice(277:307)
```

```{r}
daily_model <- auto.arima(training %>% pull(daily_revenue))
plot.ts(daily_model$residuals)
daily_forecast <- forecast(daily_model, h=31)
plot(daily_forecast)
```

```{r}
cbind(daily_uk%>%slice(277:307), daily_forecast) %>%
  ggplot(aes(x = date)) +
  geom_line(aes(y = daily_revenue), color = "black") +
  geom_line(aes(y = `Point Forecast`), color = "blue")
```

```{r}
training_hourly <- hourly_uk %>% as.data.frame() %>% slice(1:2663)
testing_hourly <- hourly_uk %>% as.data.frame() %>% slice_tail(n = 296)
```

```{r}
hourly_model <- auto.arima(training_hourly %>% pull(hourly_revenue))
plot.ts(hourly_model$residuals)
hourly_forecast <- forecast(hourly_model, h=296)
plot(hourly_forecast)
```

```{r}
cbind(testing_hourly, hourly_forecast$mean) %>%
  group_by(date) %>%
  summarize(
    daily_revenue = sum(hourly_revenue), 
    daily_forecast = sum(`hourly_forecast$mean`)
    ) %>%
  ggplot(aes(x = date)) +
  geom_line(aes(y = daily_revenue), color = "black") +
  geom_line(aes(y = daily_forecast), color = "blue") +
  scale_y_continuous(labels = label_dollar(
    scale = .001, 
    suffix = "k",,
    prefix = "£"
    )) +
  labs(
    x = "Date",
    y = "Revenue (sterling)",
    title = "Predicted vs actual revenue during last month of data set",
    subtitle = "Actual (black), predicted (blue)"
  ) +
  theme_minimal()
```
