---
title: "United Kingdom analysis"
author: "Margaret Reed"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F)
```

```{r load-library}
library(tidyverse)
library(prophet)
library(readxl)
library(janitor)
library(lubridate)
library(scales)
library(MLmetrics)
library(timeDate)
source("make-model.R")
```



```{r model, cache = T}
UK_model <- make_model("United Kingdom")
forecast <- UK_model[[1]]
testing <- UK_model[[2]]
og_data <- UK_model[[3]]
```

```{r clean-test}
z = dim(testing)[1]
x = dim(forecast)[1]

pred_test <- forecast %>%
  slice_tail(n=z) %>%
  pull(yhat)

true_test <- testing %>%
  pull(y)
```


```{r plot-pred}
full_join(og_data, forecast) %>%
  ggplot() +
  geom_line(aes(x = ymd(ds), y = y), color = "black") +
  geom_line(aes(x = ymd(ds), y = yhat), color = "blue") +
  scale_y_continuous(labels = label_dollar(
    scale = .001, 
    suffix = "k",
    prefix = "£"
    )) +
  labs(
    x = "Date",
    y = "Revenue (sterling)",
    title = "Predicted vs actual revenue",
    subtitle = "Actual (black), predicted (blue)"
  ) +
  theme_minimal() +
  geom_line(data = og_data%>%slice_head(n=x-z), aes(x = ymd(ds), y = y), color = "grey")
```

```{r MAPE-calc}
s <- round(z/3, 0)

MAPE(pred_test[1:s], true_test[1:s])
MAPE(pred_test[(s+1):(2*s)], true_test[(s+1):(2*s)])
MAPE(pred_test[(2*s+1):(3*s)], true_test[(2*s+1):(3*s)])
```



```{r boxplot}
tibble(
 first = map2_dbl(pred_test[1:s], true_test[1:s], MAPE),
 second = map2_dbl(pred_test[(s+1):(2*s)], true_test[(s+1):(2*s)], MAPE),
third = map2_dbl(pred_test[(2*s+1):(3*s)], true_test[(2*s+1):(3*s)], MAPE)
) %>%
  pivot_longer(
    cols = everything(),
    names_to = "segment",
    values_to = "error"
  ) %>%
  ggplot(aes(x = error, y = segment)) +
  geom_boxplot() +
  labs(
    x = "Error (MAPE)",
    y = "Third of testing data",
    title = "Boxplots of errors"
  ) +
  theme_minimal()
```


